import {fn, fun, str} from './module.mjs'

export const omega = 'some string'

// (import `(foo bar baz) "./jsmodule.mjs")
// single line comment
// also this ^^
function sumlists  (lista, listb)  {
  return is_null(lista) ? []  :  [(car(lista) * car(listb)), ...sumlists(cdr(lista), cdr(listb))]
}

function fact  (n)  {
  return ((n === 0.0) || (n === 1.0)) ? 1.0  :  (n * fact((n - 1.0)))
}

function map  (list, fn)  {
  return is_null(list) ? []  :  [fn(car(list)), ...map(cdr(list), fn)]
}

console.log('(let ((foo (+ 1 2)) (bar (* 3 4))) (+ foo bar))')
println(((foo, bar) => (foo + bar))((1.0 + 2.0), (3.0 * 4.0)))
// (println (letrec ((fact (lambda (n) (if (= n 0) 1 (* n (fact (- n 1))) )))) (fact 3) ))
console.log('(sumlists `(1 2 3 4) `(3 2 1 5) )')
println(sumlists([1.0, 2.0, 3.0, 4.0], [3.0, 2.0, 1.0, 5.0]))
console.log('(and true (or false true))')
println((true && (false || true)))
console.log('(map `(1 2 3 4 5) (lambda (n) (* n n)))')
println(map([1.0, 2.0, 3.0, 4.0, 5.0],  (n) => ((n * n)) ))
console.log('(fact 5)')
println(fact(5.0))
console.log('`(1 2 3 4 ,(* 6 (+ 2 3)))')
println([1.0, 2.0, 3.0, 4.0, (6.0 * (2.0 + 3.0))])
console.log('`(1 2 3 4 ,(* 6 (+ 2 `(23 24 25))))')
println([1.0, 2.0, 3.0, 4.0, (6.0 * (2.0 + [23.0, 24.0, 25.0]))])
console.log('`(,(fn 2 3) ,(fun 2 3)')
println([fn(2.0, 3.0), fun(2.0, 3.0)])
console.log('str')
println(str)
console.log('END')

///////////////////////////////////////////////////////
// THIS IS GENERATED BY THE COMPILER - DO NOT MODIFY //
function is_null (x) {                               //
  return (x instanceof Array) && (x.length === 0)    //
}                                                    //
                                                     //
function car ([x, ...xs]) {                          //
  return x                                           //
}                                                    //
                                                     //
function cdr ([x, ...xs]) {                          //
  return xs                                          //
}                                                    //
                                                     //
function println (...args) {                         //
  console.log(...args)                               //
}                                                    //
// THIS IS GENERATED BY THE COMPILER - DO NOT MODIFY //
///////////////////////////////////////////////////////
