export const fn =  (a, b) => ((a + b)) 

export { fun }

function fun  (a, b)  {
  return(a * b)
}

export const str = 'some amazing string'


///////////////////////////////////////////////////////
// THIS IS GENERATED BY THE COMPILER - DO NOT MODIFY //
function is_null (x) {                               //
  return (x instanceof Array) && (x.length === 0)    //
}                                                    //
                                                     //
function car ([x, ...xs]) {                          //
  return x                                           //
}                                                    //
                                                     //
function cdr ([x, ...xs]) {                          //
  return xs                                          //
}                                                    //
                                                     //
function println (...args) {                         //
  console.log(...args)                               //
}                                                    //
// THIS IS GENERATED BY THE COMPILER - DO NOT MODIFY //
///////////////////////////////////////////////////////
